/**
 * California Castle REST API
 * Rest API created for California Castle website project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import LocationLocationIdDeleteRequest from './models/LocationLocationIdDeleteRequest';
import LocationLocationPostRequest from './models/LocationLocationPostRequest';
import LocationApi from './api/LocationApi';
import ServerApi from './api/ServerApi';
import SwaggerApi from './api/SwaggerApi';


/**
* Rest API created for California Castle website project..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CaliforniaCastleRestApi = require('index'); // See note below*.
* var xxxSvc = new CaliforniaCastleRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CaliforniaCastleRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CaliforniaCastleRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CaliforniaCastleRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The LocationLocationIdDeleteRequest model constructor.
     * @property {module:models/LocationLocationIdDeleteRequest}
     */
    LocationLocationIdDeleteRequest,

    /**
     * The LocationLocationPostRequest model constructor.
     * @property {module:models/LocationLocationPostRequest}
     */
    LocationLocationPostRequest,

    /**
    * The LocationApi service constructor.
    * @property {module:api/LocationApi}
    */
    LocationApi,

    /**
    * The ServerApi service constructor.
    * @property {module:api/ServerApi}
    */
    ServerApi,

    /**
    * The SwaggerApi service constructor.
    * @property {module:api/SwaggerApi}
    */
    SwaggerApi
};
