/**
 * California Castle REST API
 * Rest API created for California Castle website project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CaliforniaCastleRestApi);
  }
}(this, function(expect, CaliforniaCastleRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CaliforniaCastleRestApi.LocationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LocationApi', function() {
    describe('locationLocationIdDelete', function() {
      it('should call locationLocationIdDelete successfully', function(done) {
        //uncomment below and update the code to test locationLocationIdDelete
        //instance.locationLocationIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('locationLocationIdGet', function() {
      it('should call locationLocationIdGet successfully', function(done) {
        //uncomment below and update the code to test locationLocationIdGet
        //instance.locationLocationIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('locationLocationIdPatch', function() {
      it('should call locationLocationIdPatch successfully', function(done) {
        //uncomment below and update the code to test locationLocationIdPatch
        //instance.locationLocationIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('locationLocationPost', function() {
      it('should call locationLocationPost successfully', function(done) {
        //uncomment below and update the code to test locationLocationPost
        //instance.locationLocationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('locationLocationsGet', function() {
      it('should call locationLocationsGet successfully', function(done) {
        //uncomment below and update the code to test locationLocationsGet
        //instance.locationLocationsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
